### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by hoangdung3498** [linhlv-soict/eKYC_mobile_app#1]
2024-05-13 22:41:50 Permission denied: https://drive.google.com/uc?id=1nTKlEog9YFK74kPyX0qLwCWi60_YHHk4
2024-05-13 22:41:50 Maybe you need to change permission over 'Anyone with the link'?
2024-05-13 22:41:50 Traceback (most recent call last):
2024-05-13 22:41:50   File "/usr/lib/python3.6/shutil.py", line 550, in move
2024-05-13 22:41:50     os.rename(src, real_dst)
2024-05-13 22:39:58 loading ai_model/model-r50-am-lfw/model 0
2024-05-13 22:41:50 loading ai_model/model-r50-am-lfw/model 0
2024-05-13 22:41:50 FileNotFoundError: [Errno 2] No such file or directory: '/root/.cache/gdown/tmpwjrxwhn2/dl' -> '/root/.cache/gdown/https-COLON--SLASH--SLASH-drive.google.com-SLASH-uc-QUESTION-id-EQUAL-1nTKlEog9YFK74kPyX0qLwCWi60_YHHk4'
2024-05-13 22:41:50 
2024-05-13 22:41:50 During handling of the above exception, another exception occurred:
2024-05-13 22:41:50 
2024-05-13 22:41:50 Traceback (most recent call last):
2024-05-13 22:41:50   File "/home/thuan/Desktop/tich-hop-httt/app.py", line 3, in <module>
2024-05-13 22:41:50   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
2024-05-13 22:41:50   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
2024-05-13 22:41:50   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
2024-05-13 22:41:50   File "/home/thuan/Desktop/tich-hop-httt/router/IDRouter.py", line 8, in <module router.IDRouter>
2024-05-13 22:41:50   File "/home/thuan/Desktop/tich-hop-httt/service/IDService.py", line 47, in __init__
2024-05-13 22:41:50   File "/usr/local/lib/python3.6/dist-packages/vietocr/tool/predictor.py", line 15, in __init__
2024-05-13 22:41:50     weights = download_weights(config['weights'])
2024-05-13 22:41:50   File "/usr/local/lib/python3.6/dist-packages/vietocr/tool/utils.py", line 14, in download_weights
2024-05-13 22:41:50     return gdown.cached_download(url=url, path=cached, md5=md5, quiet=quiet)
2024-05-13 22:41:50   File "/usr/local/lib/python3.6/dist-packages/gdown/cached_download.py", line 125, in cached_download
2024-05-13 22:41:50     shutil.move(temp_path, path)
2024-05-13 22:41:50   File "/usr/lib/python3.6/shutil.py", line 564, in move
2024-05-13 22:41:50     copy_function(src, real_dst)
2024-05-13 22:41:50   File "/usr/lib/python3.6/shutil.py", line 263, in copy2
2024-05-13 22:41:50     copyfile(src, dst, follow_symlinks=follow_symlinks)
2024-05-13 22:41:50   File "/usr/lib/python3.6/shutil.py", line 120, in copyfile
2024-05-13 22:41:50     with open(src, 'rb') as fsrc:
2024-05-13 22:41:50 FileNotFoundError: [Errno 2] No such file or directory: '/root/.cache/gdown/tmpwjrxwhn2/dl'

**Comment by linhlv-soict** [comment]
The model was contributed by another team member, and now it is no more available.
You can mock the back-end service according to the API used in front-end.
Thank you.
